package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	lexicon "github.com/jphein/lexicon.realm.watch/go"
)

// cmdCatalogRender produces an LLM-readable artifact from catalog/projects.yaml.
// Two formats are supported: "skill" (a SKILL.md with frontmatter, suitable for
// dropping into ~/.claude/skills/project-catalog/) and "md-table" (a GitHub-
// flavored markdown table for human review). Output goes to stdout unless
// --out is given.
//
// The render is pure data → text — no I/O beyond loading the catalog and
// writing the result. See docs/superpowers/specs/2026-05-07-catalog-render-skill.md.
func cmdCatalogRender(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("catalog render", flag.ContinueOnError)
	fs.SetOutput(stderr)
	catalog := fs.String("catalog", "", "path to catalog/projects.yaml")
	format := fs.String("format", "skill", "output format: skill | md-table")
	outPath := fs.String("out", "", "output path (default stdout)")
	if err := fs.Parse(args); err != nil {
		return 2
	}

	cat, err := lexicon.LoadCatalog(resolveCatalogPath(*catalog))
	if err != nil {
		fmt.Fprintf(stderr, "load catalog: %v\n", err)
		return 1
	}

	var rendered []byte
	switch *format {
	case "skill":
		rendered = renderSkill(cat)
	case "md-table":
		rendered = renderMDTable(cat)
	default:
		fmt.Fprintf(stderr, "unknown --format %q (valid: skill, md-table)\n", *format)
		return 2
	}

	if *outPath == "" {
		_, _ = stdout.Write(rendered)
		return 0
	}
	if err := os.WriteFile(*outPath, rendered, 0o644); err != nil {
		fmt.Fprintf(stderr, "write %s: %v\n", *outPath, err)
		return 1
	}
	return 0
}

// renderSkill emits a complete SKILL.md (frontmatter + body) describing the
// catalog. Projects are grouped by status and sorted by current_name within
// each group. Status group order is fixed for the well-known statuses
// (active, local-only, archived); any other statuses follow in alphabetical
// order so unfamiliar values surface deterministically rather than scattering.
func renderSkill(cat *lexicon.Catalog) []byte {
	var buf bytes.Buffer

	buf.WriteString("---\n")
	buf.WriteString("name: project-catalog\n")
	buf.WriteString("description: Use to look up JP's projects under ~/Projects/. Auto-loads when identifying what a project does, where it lives, what tech it uses, or which project handles a given concern.\n")
	buf.WriteString("---\n\n")

	buf.WriteString("# Project Catalog\n\n")
	buf.WriteString("Source of truth: `~/Projects/lexicon.realm.watch/catalog/projects.yaml`.\n")
	buf.WriteString("This file is generated by `lexicon catalog render --format=skill` — do not hand-edit; edit the YAML and regenerate.\n\n")

	buf.WriteString("## How to read\n\n")
	buf.WriteString("Each project below lists: directory path, kind/realm/status badge, one-line description, and notes when present. Use the path to `cd`; use the description to confirm relevance; consult the project's own `CLAUDE.md` for sub-component / plugin / internal detail.\n\n")

	if len(cat.Projects) == 0 {
		buf.WriteString("_No projects in the catalog yet._\n")
		return buf.Bytes()
	}

	for _, group := range groupProjectsByStatus(cat.Projects) {
		fmt.Fprintf(&buf, "## Projects (%s)\n\n", group.status)
		for _, p := range group.projects {
			writeSkillEntry(&buf, p)
		}
	}

	return buf.Bytes()
}

// writeSkillEntry renders a single project as one section in the skill body.
func writeSkillEntry(buf *bytes.Buffer, p *lexicon.Project) {
	heading := p.ID
	if p.CurrentName != "" && p.CurrentName != p.ID {
		heading = fmt.Sprintf("%s (`%s`)", p.ID, p.CurrentName)
	}
	fmt.Fprintf(buf, "### %s\n", heading)

	dirName := p.CurrentName
	if dirName == "" {
		dirName = p.ID
	}
	fmt.Fprintf(buf, "- **Path:** `~/Projects/%s/`\n", dirName)

	fmt.Fprintf(buf, "- **Kind:** %s · **Realm:** %s · **Status:** %s\n",
		valueOrDash(p.Kind), valueOrDash(p.Realm), valueOrDash(p.Status))

	if p.Description != "" {
		fmt.Fprintf(buf, "- %s\n", p.Description)
	}
	if p.Notes != "" {
		fmt.Fprintf(buf, "- Notes: %s\n", p.Notes)
	}
	if p.Repo != "" && p.Repo != "~" {
		fmt.Fprintf(buf, "- Repo: <%s>\n", p.Repo)
	}
	buf.WriteString("\n")
}

// renderMDTable emits a single GitHub-flavored markdown table — the shape
// currently used by ~/CLAUDE.md. One row per project, sorted by current_name.
// "Key Tech" is left as "—" for v1 since the schema doesn't track it; the
// "Notes" column collapses repo + realm + notes into a semicolon list.
func renderMDTable(cat *lexicon.Catalog) []byte {
	var buf bytes.Buffer
	buf.WriteString("| Project | What | Key Tech | Notes |\n")
	buf.WriteString("|---------|------|----------|-------|\n")

	if len(cat.Projects) == 0 {
		return buf.Bytes()
	}

	sorted := append([]*lexicon.Project(nil), cat.Projects...)
	sort.SliceStable(sorted, func(i, j int) bool {
		return sortKey(sorted[i]) < sortKey(sorted[j])
	})

	for _, p := range sorted {
		name := p.CurrentName
		if name == "" {
			name = p.ID
		}
		desc := strings.ReplaceAll(p.Description, "|", `\|`)
		if desc == "" {
			desc = "—"
		}
		fmt.Fprintf(&buf, "| **%s** | %s | — | %s |\n",
			strings.ReplaceAll(name, "|", `\|`),
			desc,
			mdTableNotes(p))
	}

	return buf.Bytes()
}

// mdTableNotes assembles the rightmost cell from repo + realm + notes.
func mdTableNotes(p *lexicon.Project) string {
	var parts []string
	if p.Repo != "" && p.Repo != "~" {
		parts = append(parts, fmt.Sprintf("[GitHub](%s)", p.Repo))
	}
	if p.Realm != "" && p.Realm != "~" && p.Realm != "?" {
		parts = append(parts, fmt.Sprintf("Realm: %s", p.Realm))
	}
	if p.Notes != "" {
		parts = append(parts, strings.ReplaceAll(p.Notes, "|", `\|`))
	}
	if len(parts) == 0 {
		return "—"
	}
	return strings.Join(parts, "; ")
}

// statusGroup holds one status bucket of projects, in render order.
type statusGroup struct {
	status   string
	projects []*lexicon.Project
}

// groupProjectsByStatus partitions projects by status with a stable, predictable
// order: active first, then local-only, then archived, then any other statuses
// alphabetically. Within each group, projects sort by current_name (or id if
// current_name is unset).
func groupProjectsByStatus(projects []*lexicon.Project) []statusGroup {
	bucketed := map[string][]*lexicon.Project{}
	for _, p := range projects {
		s := p.Status
		if s == "" {
			s = "(unknown)"
		}
		bucketed[s] = append(bucketed[s], p)
	}

	for s := range bucketed {
		sort.SliceStable(bucketed[s], func(i, j int) bool {
			return sortKey(bucketed[s][i]) < sortKey(bucketed[s][j])
		})
	}

	preferred := []string{"active", "local-only", "archived"}
	out := make([]statusGroup, 0, len(bucketed))
	for _, s := range preferred {
		if ps, ok := bucketed[s]; ok {
			out = append(out, statusGroup{status: s, projects: ps})
			delete(bucketed, s)
		}
	}

	rest := make([]string, 0, len(bucketed))
	for s := range bucketed {
		rest = append(rest, s)
	}
	sort.Strings(rest)
	for _, s := range rest {
		out = append(out, statusGroup{status: s, projects: bucketed[s]})
	}
	return out
}

// sortKey returns the string used to order a project within its status group.
func sortKey(p *lexicon.Project) string {
	if p.CurrentName != "" {
		return p.CurrentName
	}
	return p.ID
}

// valueOrDash returns "—" for empty / placeholder values so the operator can
// see gaps in the YAML at a glance.
func valueOrDash(s string) string {
	if s == "" || s == "~" || s == "?" {
		return "—"
	}
	return s
}
